site_name: RP-8 User Guide
nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Reference: reference.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: True
plugins:
  - search
  - pdf-export:
      verbose: True
      media_type: print
      combined: True
      combined_output_path: pdf/combined.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
  - minify:
      minify_html: true
