site_name: RP-8 User Guide
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Reference: reference.md
  - Contact: contact.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: True
plugins:
  - search
  - minify:
      minify_html: true
  - print-site:
      print_page_title: 'RP-8 User Guide'
      toc_depth: 3
